# Site settings
title: Find a Page
email: lrlanswer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Do you love coding? I am.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://realli.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: realli

# Build settings
markdown: kramdown
